version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    restart: always
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: python3 bot_script.py