version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - API_URL=${API_URL}
    volumes:
      - .:/usr/src/app
    command: python3 bot_script.py
    env_file:
      - .env